/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class Ventana_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Cliente
     */
    
    public Ventana_Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloVentanaCliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        AreaTxtIP = new javax.swing.JTextField();
        BotonConectar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloVentanaCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloVentanaCliente.setText("Cliente");

        jLabel1.setText("Seleccione su estación:");

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "Estación 1", "Estación 2", "Estación 3", "Estación 4" }));

        jLabel2.setText("Dirección IP:");

        BotonConectar.setText("Conectar");
        BotonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConectarActionPerformed(evt);
            }
        });

        jButton1.setText("Ir a Ventana Principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(TituloVentanaCliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AreaTxtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(BotonConectar))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(TituloVentanaCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AreaTxtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addComponent(BotonConectar)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConectarActionPerformed
        // TODO add your handling code here:
        String IP="";
   
    
       int opcion = ComboBox.getSelectedIndex();
      
        if(opcion ==0 ){
         JOptionPane.showMessageDialog(this, "Seleccione una estacion");
         
        }
   
       if(AreaTxtIP.getText().equals("")){
           JOptionPane.showMessageDialog(null,"No ingreso direccion IP\n",null,JOptionPane.PLAIN_MESSAGE);
       }if (opcion!=0 && !"".equals(AreaTxtIP.getText())){ IP = AreaTxtIP.getText();
       System.out.println(IP);
       
      String opcion2= Integer.toString(opcion); // transformo la opcion seleccionada de entero a string para manejarlo en la clase cliente
         
      if( "1".equals(opcion2)){
          
       
        Estacion1 E1 = new Estacion1(IP);
        E1.setLocationRelativeTo(null);
        E1.setTitle("Colector de retrasos");
        E1.setResizable(false);
        E1.setVisible(true);
        E1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
          
        }
         if("2".equals(opcion2)){
        Estacion2 E2 = new Estacion2(IP);
        E2.setLocationRelativeTo(null);
        E2.setTitle("Colector de retrasos");
        E2.setResizable(false);
        E2.setVisible(true);
        E2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       
        }
          if("3".equals(opcion2)){
        Estacion3 E3 = new Estacion3(IP);
        E3.setLocationRelativeTo(null);
        E3.setTitle("Colector de retrasos");
        E3.setResizable(false);
        E3.setVisible(true);
        E3.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        }
           if("4".equals(opcion2)){
        Estacion4 E4 = new Estacion4(IP);
        E4.setLocationRelativeTo(null);
        E4.setTitle("Colector de retrasos");
        E4.setResizable(false);
        E4.setVisible(true);
        E4.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       
        }      // se envian por parametros en vez de por clases
      this.setVisible(false);
    }//GEN-LAST:event_BotonConectarActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Frames.Ventana VentanaPrincipal = new Frames.Ventana();
        VentanaPrincipal.setLocationRelativeTo(null);
        VentanaPrincipal.setTitle("App Lab CIM");
        VentanaPrincipal.setVisible(true);
        VentanaPrincipal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AreaTxtIP;
    private javax.swing.JButton BotonConectar;
    private javax.swing.JComboBox ComboBox;
    private javax.swing.JLabel TituloVentanaCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
