/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Carlos
 */
public class Ventana_Servidor extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Servidor
     */
    public String[] datos;
    public String[] dato;
    public String robot1;
    public String robot2;
    public String robot3;
    public String fresadora;
    public String torno;
    public String vision;
    public String conveyor;
    public App.Servidor nuevo;
    private JPanel jpanel;
	private String Nombre;
	private String Codigo;
	private JComboBox calculoProb;
	private JTextField Valor;
	private JRadioButton Acepted;
	private boolean Aceptado;
	private int NumArea;
	ActionListener actionListener;

	private float  ValorACEPTADO= 0;
    
    public Ventana_Servidor() {
        initComponents();
    }

    Ventana_Servidor(Ventana aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TituloVentanaServidor = new javax.swing.JLabel();
        PanelEstacion1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelRobot1 = new javax.swing.JLabel();
        AreaTextR1 = new javax.swing.JTextField();
        jComboBoxR1 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        PanelEstacion2 = new javax.swing.JPanel();
        labelEstacion2 = new javax.swing.JLabel();
        labelRobot2 = new javax.swing.JLabel();
        LabelTorno = new javax.swing.JLabel();
        labelFresadora = new javax.swing.JLabel();
        AreaTextR2 = new javax.swing.JTextField();
        AreaTextFr = new javax.swing.JTextField();
        AreaTextTr = new javax.swing.JTextField();
        ComboBoxR2 = new javax.swing.JComboBox();
        jComboBoxFr = new javax.swing.JComboBox();
        jComboBoxTr = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        PanelEstacion3 = new javax.swing.JPanel();
        labelEstacion3 = new javax.swing.JLabel();
        labelRobot3 = new javax.swing.JLabel();
        labelVision1 = new javax.swing.JLabel();
        AreaTextR3 = new javax.swing.JTextField();
        AreaTextVs1 = new javax.swing.JTextField();
        ComboBoxR3 = new javax.swing.JComboBox();
        jComboBoxV1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        PanelEstacion4 = new javax.swing.JPanel();
        labelEstacion4 = new javax.swing.JLabel();
        labelConveyor = new javax.swing.JLabel();
        AreaTextCv = new javax.swing.JTextField();
        jComboBoxCv = new javax.swing.JComboBox();
        jButton9 = new javax.swing.JButton();
        BotonEstablecer = new javax.swing.JButton();
        botonDetener = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        botonAbrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Configuraciones:");

        TituloVentanaServidor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TituloVentanaServidor.setText("Servidor");

        PanelEstacion1.setBackground(new java.awt.Color(153, 153, 255));
        PanelEstacion1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Estación 1");

        labelRobot1.setText("Robot 1:");

        AreaTextR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaTextR1ActionPerformed(evt);
            }
        });

        jComboBoxR1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "1. Distribución t de Students", "2. Distribución Exponencial", "3. Distribución Laplace", "4. Distribución Normal Estandar", "5. Distribución Poisson", "6. Distribución Uniforme", "7. Distribución Weibull", "8. Congruencia Lineal" }));
        jComboBoxR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxR1ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Carlos\\Documents\\NetBeansProjects\\Proyecto00\\src\\Icons\\play.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEstacion1Layout = new javax.swing.GroupLayout(PanelEstacion1);
        PanelEstacion1.setLayout(PanelEstacion1Layout);
        PanelEstacion1Layout.setHorizontalGroup(
            PanelEstacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstacion1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEstacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(labelRobot1))
                .addGap(18, 18, 18)
                .addGroup(PanelEstacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AreaTextR1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelEstacion1Layout.setVerticalGroup(
            PanelEstacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstacion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(PanelEstacion1Layout.createSequentialGroup()
                        .addGroup(PanelEstacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRobot1)
                            .addComponent(jComboBoxR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AreaTextR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelEstacion2.setBackground(new java.awt.Color(153, 153, 255));
        PanelEstacion2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelEstacion2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelEstacion2.setText("Estación 2");

        labelRobot2.setText("Robot 2:");

        LabelTorno.setText("Torno:");

        labelFresadora.setText("Fresadora:");

        AreaTextR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaTextR2ActionPerformed(evt);
            }
        });

        ComboBoxR2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "1. Distribución t de Students", "2. Distribución Exponencial", "3. Distribución Laplace", "4. Distribución Normal Estandar", "5. Distribución Poisson", "6. Distribución Uniforme", "7. Distribución Weibull", "8. Congruencia Lineal" }));

        jComboBoxFr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "1. Distribución t de Students", "2. Distribución Exponencial", "3. Distribución Laplace", "4. Distribución Normal Estandar", "5. Distribución Poisson", "6. Distribución Uniforme", "7. Distribución Weibull", "8. Congruencia Lineal" }));

        jComboBoxTr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "1. Distribución t de Students", "2. Distribución Exponencial", "3. Distribución Laplace", "4. Distribución Normal Estandar", "5. Distribución Poisson", "6. Distribución Uniforme", "7. Distribución Weibull", "8. Congruencia Lineal" }));

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Carlos\\Documents\\NetBeansProjects\\Proyecto00\\src\\Icons\\play.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Carlos\\Documents\\NetBeansProjects\\Proyecto00\\src\\Icons\\play.png")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Carlos\\Documents\\NetBeansProjects\\Proyecto00\\src\\Icons\\play.png")); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEstacion2Layout = new javax.swing.GroupLayout(PanelEstacion2);
        PanelEstacion2.setLayout(PanelEstacion2Layout);
        PanelEstacion2Layout.setHorizontalGroup(
            PanelEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstacion2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEstacion2Layout.createSequentialGroup()
                        .addGroup(PanelEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEstacion2Layout.createSequentialGroup()
                                .addComponent(labelFresadora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxFr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AreaTextFr, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelEstacion2Layout.createSequentialGroup()
                                .addComponent(LabelTorno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AreaTextTr, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxTr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(PanelEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addComponent(jButton8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelEstacion2Layout.createSequentialGroup()
                        .addGroup(PanelEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEstacion2Layout.createSequentialGroup()
                                .addComponent(labelRobot2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboBoxR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AreaTextR2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton6))
                            .addComponent(labelEstacion2))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        PanelEstacion2Layout.setVerticalGroup(
            PanelEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstacion2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEstacion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEstacion2Layout.createSequentialGroup()
                        .addGroup(PanelEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRobot2)
                            .addComponent(ComboBoxR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AreaTextR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEstacion2Layout.createSequentialGroup()
                        .addGroup(PanelEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelFresadora)
                            .addComponent(jComboBoxFr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AreaTextFr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEstacion2Layout.createSequentialGroup()
                        .addGroup(PanelEstacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTorno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AreaTextTr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton8))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        PanelEstacion3.setBackground(new java.awt.Color(153, 153, 255));
        PanelEstacion3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelEstacion3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelEstacion3.setText("Estación 3");

        labelRobot3.setText("Robot 3:");

        labelVision1.setText("Visión 1:");

        ComboBoxR3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "1. Distribución t de Students", "2. Distribución Exponencial", "3. Distribución Laplace", "4. Distribución Normal Estandar", "5. Distribución Poisson", "6. Distribución Uniforme", "7. Distribución Weibull", "8. Congruencia Lineal" }));

        jComboBoxV1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "1. Distribución t de Students", "2. Distribución Exponencial", "3. Distribución Laplace", "4. Distribución Normal Estandar", "5. Distribución Poisson", "6. Distribución Uniforme", "7. Distribución Weibull", "8. Congruencia Lineal" }));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Carlos\\Documents\\NetBeansProjects\\Proyecto00\\src\\Icons\\play.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Carlos\\Documents\\NetBeansProjects\\Proyecto00\\src\\Icons\\play.png")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEstacion3Layout = new javax.swing.GroupLayout(PanelEstacion3);
        PanelEstacion3.setLayout(PanelEstacion3Layout);
        PanelEstacion3Layout.setHorizontalGroup(
            PanelEstacion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstacion3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEstacion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEstacion3Layout.createSequentialGroup()
                        .addComponent(labelRobot3)
                        .addGap(18, 18, 18)
                        .addGroup(PanelEstacion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AreaTextR3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxR3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelEstacion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton5)))
                    .addComponent(labelEstacion3)
                    .addGroup(PanelEstacion3Layout.createSequentialGroup()
                        .addComponent(labelVision1)
                        .addGap(18, 18, 18)
                        .addGroup(PanelEstacion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AreaTextVs1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelEstacion3Layout.setVerticalGroup(
            PanelEstacion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstacion3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEstacion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstacion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEstacion3Layout.createSequentialGroup()
                        .addGroup(PanelEstacion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRobot3)
                            .addComponent(ComboBoxR3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AreaTextR3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(PanelEstacion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelEstacion3Layout.createSequentialGroup()
                                .addComponent(jComboBoxV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AreaTextVs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelVision1)))
                    .addGroup(PanelEstacion3Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        PanelEstacion4.setBackground(new java.awt.Color(153, 153, 255));
        PanelEstacion4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelEstacion4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelEstacion4.setText("Estación 4");

        labelConveyor.setText("Conveyor:");

        AreaTextCv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaTextCvActionPerformed(evt);
            }
        });

        jComboBoxCv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "1. Distribución t de Students", "2. Distribución Exponencial", "3. Distribución Laplace", "4. Distribución Normal Estandar", "5. Distribución Poisson", "6. Distribución Uniforme", "7. Distribución Weibull", "8. Congruencia Lineal" }));

        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Carlos\\Documents\\NetBeansProjects\\Proyecto00\\src\\Icons\\play.png")); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEstacion4Layout = new javax.swing.GroupLayout(PanelEstacion4);
        PanelEstacion4.setLayout(PanelEstacion4Layout);
        PanelEstacion4Layout.setHorizontalGroup(
            PanelEstacion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstacion4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelEstacion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEstacion4)
                    .addGroup(PanelEstacion4Layout.createSequentialGroup()
                        .addComponent(labelConveyor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelEstacion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AreaTextCv, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        PanelEstacion4Layout.setVerticalGroup(
            PanelEstacion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstacion4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEstacion4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstacion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEstacion4Layout.createSequentialGroup()
                        .addGroup(PanelEstacion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelConveyor)
                            .addComponent(jComboBoxCv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AreaTextCv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BotonEstablecer.setText("Establecer Parametros");
        BotonEstablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEstablecerActionPerformed(evt);
            }
        });

        botonDetener.setText("Detener Conexiones");
        botonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetenerActionPerformed(evt);
            }
        });

        botonVolver.setText("Ir a Ventana Principal");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonAbrir.setText("Abrir desde archivo txt");
        botonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(TituloVentanaServidor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonAbrir)
                                .addGap(18, 18, 18)
                                .addComponent(BotonEstablecer))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PanelEstacion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PanelEstacion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(botonVolver)
                                            .addGap(42, 42, 42)
                                            .addComponent(botonDetener))
                                        .addComponent(PanelEstacion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(PanelEstacion2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(TituloVentanaServidor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BotonEstablecer)
                    .addComponent(botonAbrir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelEstacion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelEstacion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelEstacion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelEstacion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVolver)
                    .addComponent(botonDetener))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        Frames.Ventana VentanaPrincipal = new Frames.Ventana();
        VentanaPrincipal.setLocationRelativeTo(null);
        VentanaPrincipal.setTitle("App Lab CIM");
        VentanaPrincipal.setVisible(true);
        VentanaPrincipal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(false);
        
    }//GEN-LAST:event_botonVolverActionPerformed

    private void AreaTextR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaTextR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaTextR2ActionPerformed

    private void botonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbrirActionPerformed
        // TODO add your handling code here:
        Seleccionar dialog = new Seleccionar(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        //  dialog.direccion.mensaje.leer();  //de esta forma puedo acceder a el metodo
        datos= new String[dialog.direccion.mensaje.obtenerLargo()];
        datos=dialog.direccion.mensaje.obtenerMensaje();
        // System.out.println(datos[0]); // era para probar si capturaba
       for(int i=0;i<dialog.direccion.mensaje.obtenerLargo();i++){
           
            String[] arraySepara=datos[i].split(",");
           if( arraySepara[0].equals("WS1") && arraySepara[1].equals("R1")){
               robot1 = arraySepara[2];
               
               AreaTextR1.setText(robot1);
            }
           if ( arraySepara[0].equals("WS2") && arraySepara[1].equals("R2")){
                robot2 = arraySepara[2];
                AreaTextR2.setText(robot2);
           }
            if ( arraySepara[0].equals("WS2") && arraySepara[1].equals("F1")){
                fresadora = arraySepara[2];
                AreaTextFr.setText(fresadora);
           }
            if ( arraySepara[0].equals("WS2") && arraySepara[1].equals("T1")){
                torno = arraySepara[2];
                AreaTextTr.setText(torno);
           }
             if ( arraySepara[0].equals("WS3") && arraySepara[1].equals("R3")){
                robot3 = arraySepara[2];
                AreaTextR3.setText(robot3);
           }
              if ( arraySepara[0].equals("WS3") && arraySepara[1].equals("V1")){
                vision = arraySepara[2];
                AreaTextVs1.setText(vision);
           }
               if ( arraySepara[0].equals("WS1") && arraySepara[1].equals("PLC1")){
                conveyor = arraySepara[2];
                AreaTextCv.setText(conveyor);
           }
        }
    }//GEN-LAST:event_botonAbrirActionPerformed

    private void BotonEstablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEstablecerActionPerformed
        // TODO add your handling code here:
        robot1=AreaTextR1.getText();       
        robot2=AreaTextR2.getText();      
        robot3=AreaTextR3.getText();
        fresadora=AreaTextFr.getText();       
        torno=AreaTextTr.getText();       
        vision=AreaTextVs1.getText();
        conveyor=AreaTextCv.getText();
        
        dato= new String[7];
        
         dato[0]=robot1;
         dato[1]=robot2;
         dato[2]=fresadora;
         dato[3]=torno;
         dato[4]=robot3;
         dato[5]=vision;
         dato[6]=conveyor;
            if(dato[0].equals("")||dato[1].equals("")||dato[2].equals("")||dato[3].equals("")||
                    dato[4].equals("")||dato[5].equals("")||dato[6].equals("")){
             JOptionPane.showMessageDialog(this, "No pueden haber campos vacios");
             }else{       JOptionPane.showMessageDialog(this, "Recuerde Presionar el boton Cerrar conexion cuando realice algun cambio");
                 try {
            this.nuevo = new App.Servidor();   // este es el boton de activacion del servidor
            nuevo.Servidor(dato);
            
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
         }
            boolean pass= true;
        int i;    
        for(i=0;i<=6;i++){
            
            
        }
            File archivo;
        archivo = new File("Reporte Distribuciones.txt");
        if(archivo.exists()){
         int opcion = JOptionPane.showOptionDialog(null, "El archivo ya existe ¿ desea sobre escribir?", 
            "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null); 
            if(opcion == 0){
                 archivo.delete();
                  }
            else{ 
                pass=false;
            }
        
        }
        if(pass==true){
        try {
            FileWriter escribir=new FileWriter(archivo,true);
            
             escribir.write("$WS1"+"R1,"+dato[0]+"#"+"WS2R2,"+dato[1]+"#"+"WS2FR,"+dato[2]+"#"+"WS2TR,"+dato[3]+"#"+"WS3"+"R3,"+dato[4]+"#"+"WS3"+"V1,"+dato[5]+"#"+"WS4"+"PLC,"+dato[6]+"$");
            escribir.close();
            JOptionPane.showMessageDialog(null,"Los datos fueron guardados correctamente\n",null,JOptionPane.PLAIN_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(Estacion1.class.getName()).log(Level.SEVERE, null, ex);
        }
        } else{
        JOptionPane.showMessageDialog(null,"Los datos NO fueron almacenados\n",null,JOptionPane.PLAIN_MESSAGE);
        }
         
    }//GEN-LAST:event_BotonEstablecerActionPerformed

    private void botonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetenerActionPerformed
        // TODO add your handling code here:
         // este es el boton de activacion del servidor
        try {
            nuevo.stop();
        } catch (IOException ex) {
            Logger.getLogger(Ventana_Servidor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonDetenerActionPerformed

    private void jComboBoxR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxR1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     
                int opcion=jComboBoxR1.getSelectedIndex();
		App.Generacion_Ventanas_Emergentes GVE= new App.Generacion_Ventanas_Emergentes();
		App.Funciones_Interfaz FI = new App.Funciones_Interfaz();
		float valor=0;
                
			System.out.println("opcion: "+opcion);
			if(opcion==0){//No se ha elegido ninguna opcion
				valor=-1;
			}
			if(opcion==1){ //1	"Distribucion T de Student"
				valor= GVE.VentanaDistribucionTStudent();
			} 
			if(opcion==2){//2	"Distribucion Exponencial"
				valor= GVE.VentanaDistribucionExponencial();
			}
			if(opcion==3){//3	"Distribucion Laplace"
				valor= GVE.VentanaDistribucionLaplace();
			}
			if(opcion==4){//4	"Distribucion Normal Estandar"
				valor=GVE.VentanaDistribucionNormalEstandar();
			}
			if(opcion==5){//5	"Distribucion Poisson"
				valor= GVE.VentanaDistribucionPoisson();
			}
			if(opcion==6){//6	"Distribucion Uniforme"	
				valor= GVE.VentanaDistribucionUniforme();
			}	
			if(opcion==7){//7	"Distribucion Weibull"	
				valor= GVE.VentanaDistribucionWeibull();
			}
			if(opcion==8){//8	"Congruencia Lineal"
				valor= GVE.VentanaCongruencia_Lineal();
			}
			
			 if(valor>=0){
					if(valor>=1){
							valor=1;
					}
					String Muestra= Float.toString(valor);
					AreaTextR1.setText(Muestra);
					Acepted.setEnabled(true);
				}
			
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int opcion=ComboBoxR2.getSelectedIndex();
		App.Generacion_Ventanas_Emergentes GVE= new App.Generacion_Ventanas_Emergentes();
		App.Funciones_Interfaz FI = new App.Funciones_Interfaz();
		float valor=0;
                
			System.out.println("opcion: "+opcion);
			if(opcion==0){//No se ha elegido ninguna opcion
				valor=-1;
			}
			if(opcion==1){ //1	"Distribucion T de Student"
				valor= GVE.VentanaDistribucionTStudent();
			} 
			if(opcion==2){//2	"Distribucion Exponencial"
				valor= GVE.VentanaDistribucionExponencial();
			}
			if(opcion==3){//3	"Distribucion Laplace"
				valor= GVE.VentanaDistribucionLaplace();
			}
			if(opcion==4){//4	"Distribucion Normal Estandar"
				valor=GVE.VentanaDistribucionNormalEstandar();
			}
			if(opcion==5){//5	"Distribucion Poisson"
				valor= GVE.VentanaDistribucionPoisson();
			}
			if(opcion==6){//6	"Distribucion Uniforme"	
				valor= GVE.VentanaDistribucionUniforme();
			}	
			if(opcion==7){//7	"Distribucion Weibull"	
				valor= GVE.VentanaDistribucionWeibull();
			}
			if(opcion==8){//8	"Congruencia Lineal"
				valor= GVE.VentanaCongruencia_Lineal();
			}
			
			 if(valor>=0){
					if(valor>=1){
							valor=1;
					}
					String Muestra= Float.toString(valor);
					AreaTextR2.setText(Muestra);
					Acepted.setEnabled(true);
				}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int opcion=jComboBoxFr.getSelectedIndex();
		App.Generacion_Ventanas_Emergentes GVE= new App.Generacion_Ventanas_Emergentes();
		App.Funciones_Interfaz FI = new App.Funciones_Interfaz();
		float valor=0;
                
			System.out.println("opcion: "+opcion);
			if(opcion==0){//No se ha elegido ninguna opcion
				valor=-1;
			}
			if(opcion==1){ //1	"Distribucion T de Student"
				valor= GVE.VentanaDistribucionTStudent();
			} 
			if(opcion==2){//2	"Distribucion Exponencial"
				valor= GVE.VentanaDistribucionExponencial();
			}
			if(opcion==3){//3	"Distribucion Laplace"
				valor= GVE.VentanaDistribucionLaplace();
			}
			if(opcion==4){//4	"Distribucion Normal Estandar"
				valor=GVE.VentanaDistribucionNormalEstandar();
			}
			if(opcion==5){//5	"Distribucion Poisson"
				valor= GVE.VentanaDistribucionPoisson();
			}
			if(opcion==6){//6	"Distribucion Uniforme"	
				valor= GVE.VentanaDistribucionUniforme();
			}	
			if(opcion==7){//7	"Distribucion Weibull"	
				valor= GVE.VentanaDistribucionWeibull();
			}
			if(opcion==8){//8	"Congruencia Lineal"
				valor= GVE.VentanaCongruencia_Lineal();
			}
			
			 if(valor>=0){
					if(valor>=1){
							valor=1;
					}
					String Muestra= Float.toString(valor);
					AreaTextFr.setText(Muestra);
					Acepted.setEnabled(true);
				}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int opcion=jComboBoxTr.getSelectedIndex();
		App.Generacion_Ventanas_Emergentes GVE= new App.Generacion_Ventanas_Emergentes();
		App.Funciones_Interfaz FI = new App.Funciones_Interfaz();
		float valor=0;
                
			System.out.println("opcion: "+opcion);
			if(opcion==0){//No se ha elegido ninguna opcion
				valor=-1;
			}
			if(opcion==1){ //1	"Distribucion T de Student"
				valor= GVE.VentanaDistribucionTStudent();
			} 
			if(opcion==2){//2	"Distribucion Exponencial"
				valor= GVE.VentanaDistribucionExponencial();
			}
			if(opcion==3){//3	"Distribucion Laplace"
				valor= GVE.VentanaDistribucionLaplace();
			}
			if(opcion==4){//4	"Distribucion Normal Estandar"
				valor=GVE.VentanaDistribucionNormalEstandar();
			}
			if(opcion==5){//5	"Distribucion Poisson"
				valor= GVE.VentanaDistribucionPoisson();
			}
			if(opcion==6){//6	"Distribucion Uniforme"	
				valor= GVE.VentanaDistribucionUniforme();
			}	
			if(opcion==7){//7	"Distribucion Weibull"	
				valor= GVE.VentanaDistribucionWeibull();
			}
			if(opcion==8){//8	"Congruencia Lineal"
				valor= GVE.VentanaCongruencia_Lineal();
			}
			
			 if(valor>=0){
					if(valor>=1){
							valor=1;
					}
					String Muestra= Float.toString(valor);
					AreaTextTr.setText(Muestra);
					Acepted.setEnabled(true);
				}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int opcion=ComboBoxR3.getSelectedIndex();
		App.Generacion_Ventanas_Emergentes GVE= new App.Generacion_Ventanas_Emergentes();
		App.Funciones_Interfaz FI = new App.Funciones_Interfaz();
		float valor=0;
                
			System.out.println("opcion: "+opcion);
			if(opcion==0){//No se ha elegido ninguna opcion
				valor=-1;
			}
			if(opcion==1){ //1	"Distribucion T de Student"
				valor= GVE.VentanaDistribucionTStudent();
			} 
			if(opcion==2){//2	"Distribucion Exponencial"
				valor= GVE.VentanaDistribucionExponencial();
			}
			if(opcion==3){//3	"Distribucion Laplace"
				valor= GVE.VentanaDistribucionLaplace();
			}
			if(opcion==4){//4	"Distribucion Normal Estandar"
				valor=GVE.VentanaDistribucionNormalEstandar();
			}
			if(opcion==5){//5	"Distribucion Poisson"
				valor= GVE.VentanaDistribucionPoisson();
			}
			if(opcion==6){//6	"Distribucion Uniforme"	
				valor= GVE.VentanaDistribucionUniforme();
			}	
			if(opcion==7){//7	"Distribucion Weibull"	
				valor= GVE.VentanaDistribucionWeibull();
			}
			if(opcion==8){//8	"Congruencia Lineal"
				valor= GVE.VentanaCongruencia_Lineal();
			}
			
			 if(valor>=0){
					if(valor>=1){
							valor=1;
					}
					String Muestra= Float.toString(valor);
					AreaTextR3.setText(Muestra);
					Acepted.setEnabled(true);
				}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int opcion=jComboBoxV1.getSelectedIndex();
		App.Generacion_Ventanas_Emergentes GVE= new App.Generacion_Ventanas_Emergentes();
		App.Funciones_Interfaz FI = new App.Funciones_Interfaz();
		float valor=0;
                
			System.out.println("opcion: "+opcion);
			if(opcion==0){//No se ha elegido ninguna opcion
				valor=-1;
			}
			if(opcion==1){ //1	"Distribucion T de Student"
				valor= GVE.VentanaDistribucionTStudent();
			} 
			if(opcion==2){//2	"Distribucion Exponencial"
				valor= GVE.VentanaDistribucionExponencial();
			}
			if(opcion==3){//3	"Distribucion Laplace"
				valor= GVE.VentanaDistribucionLaplace();
			}
			if(opcion==4){//4	"Distribucion Normal Estandar"
				valor=GVE.VentanaDistribucionNormalEstandar();
			}
			if(opcion==5){//5	"Distribucion Poisson"
				valor= GVE.VentanaDistribucionPoisson();
			}
			if(opcion==6){//6	"Distribucion Uniforme"	
				valor= GVE.VentanaDistribucionUniforme();
			}	
			if(opcion==7){//7	"Distribucion Weibull"	
				valor= GVE.VentanaDistribucionWeibull();
			}
			if(opcion==8){//8	"Congruencia Lineal"
				valor= GVE.VentanaCongruencia_Lineal();
			}
			
			 if(valor>=0){
					if(valor>=1){
							valor=1;
					}
					String Muestra= Float.toString(valor);
					AreaTextVs1.setText(Muestra);
					Acepted.setEnabled(true);
				}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       int opcion=jComboBoxCv.getSelectedIndex();
		App.Generacion_Ventanas_Emergentes GVE= new App.Generacion_Ventanas_Emergentes();
		App.Funciones_Interfaz FI = new App.Funciones_Interfaz();
		float valor=0;
                
			System.out.println("opcion: "+opcion);
			if(opcion==0){//No se ha elegido ninguna opcion
				valor=-1;
			}
			if(opcion==1){ //1	"Distribucion T de Student"
				valor= GVE.VentanaDistribucionTStudent();
			} 
			if(opcion==2){//2	"Distribucion Exponencial"
				valor= GVE.VentanaDistribucionExponencial();
			}
			if(opcion==3){//3	"Distribucion Laplace"
				valor= GVE.VentanaDistribucionLaplace();
			}
			if(opcion==4){//4	"Distribucion Normal Estandar"
				valor=GVE.VentanaDistribucionNormalEstandar();
			}
			if(opcion==5){//5	"Distribucion Poisson"
				valor= GVE.VentanaDistribucionPoisson();
			}
			if(opcion==6){//6	"Distribucion Uniforme"	
				valor= GVE.VentanaDistribucionUniforme();
			}	
			if(opcion==7){//7	"Distribucion Weibull"	
				valor= GVE.VentanaDistribucionWeibull();
			}
			if(opcion==8){//8	"Congruencia Lineal"
				valor= GVE.VentanaCongruencia_Lineal();
			}
			
			 if(valor>=0){
					if(valor>=1){
							valor=1;
					}
					String Muestra= Float.toString(valor);
					AreaTextCv.setText(Muestra);
					Acepted.setEnabled(true);
				}
    }//GEN-LAST:event_jButton9ActionPerformed

    private void AreaTextCvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaTextCvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaTextCvActionPerformed

    private void AreaTextR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaTextR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaTextR1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Servidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AreaTextCv;
    private javax.swing.JTextField AreaTextFr;
    private javax.swing.JTextField AreaTextR1;
    private javax.swing.JTextField AreaTextR2;
    private javax.swing.JTextField AreaTextR3;
    private javax.swing.JTextField AreaTextTr;
    private javax.swing.JTextField AreaTextVs1;
    private javax.swing.JButton BotonEstablecer;
    private javax.swing.JComboBox ComboBoxR2;
    private javax.swing.JComboBox ComboBoxR3;
    private javax.swing.JLabel LabelTorno;
    private javax.swing.JPanel PanelEstacion1;
    private javax.swing.JPanel PanelEstacion2;
    private javax.swing.JPanel PanelEstacion3;
    private javax.swing.JPanel PanelEstacion4;
    private javax.swing.JLabel TituloVentanaServidor;
    private javax.swing.JButton botonAbrir;
    private javax.swing.JButton botonDetener;
    private javax.swing.JButton botonVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBoxCv;
    private javax.swing.JComboBox jComboBoxFr;
    private javax.swing.JComboBox jComboBoxR1;
    private javax.swing.JComboBox jComboBoxTr;
    private javax.swing.JComboBox jComboBoxV1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelConveyor;
    private javax.swing.JLabel labelEstacion2;
    private javax.swing.JLabel labelEstacion3;
    private javax.swing.JLabel labelEstacion4;
    private javax.swing.JLabel labelFresadora;
    private javax.swing.JLabel labelRobot1;
    private javax.swing.JLabel labelRobot2;
    private javax.swing.JLabel labelRobot3;
    private javax.swing.JLabel labelVision1;
    // End of variables declaration//GEN-END:variables
}
